import { Suspense } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<>HOLA</>}>{children}</Suspense>
      </body>
    </html>
  );
}
